export const TEACHER_LOGIN_LOADING = "TEACHER_LOGIN_LOADING";
export const TEACHER_LOGIN_SUCCESS = "TEACHER_LOGIN_SUCCESS";
export const TEACHER_LOGIN_ERROR = "TEACHER_LOGIN_ERROR";

export const TEACHER_PROFILE_LOADING = "TEACHER_PROFILE_LOADING";
export const TEACHER_PROFILE_SUCCESS = "TEACHER_PROFILE_SUCCESS";
export const TEACHER_PROFILE_ERROR = "TEACHER_PROFILE_ERROR";

export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";