export const TEACHER_LOGIN_LOADING = "TEACHER_LOGIN_LOADING";
export const TEACHER_LOGIN_SUCCESS = "TEACHER_LOGIN_SUCCESS";
export const TEACHER_LOGIN_ERROR = "TEACHER_LOGIN_ERROR";

export const TEACHER_FORGOT_LOADING = "TEACHER_Forgot_LOADING";
export const TEACHER_FORGOT_SUCCESS = "TEACHER_Forgot_SUCCESS";
export const TEACHER_FORGOT_ERROR = "TEACHER_Forgot_ERROR";

export const TEACHER_OTP_LOADING = "TEACHER_OTP_LOADING";
export const TEACHER_OTP_SUCCESS = "TEACHER_OTP_SUCCESS";
export const TEACHER_OTP_ERROR = "TEACHER_OTP_ERROR";

export const TEACHER_PROFILE_LOADING = "TEACHER_PROFILE_LOADING";
export const TEACHER_PROFILE_SUCCESS = "TEACHER_PROFILE_SUCCESS";
export const TEACHER_PROFILE_ERROR = "TEACHER_PROFILE_ERROR";

export const UPDATE_PROFILE_LOADING = "UPDATE_PROFILE_LOADING";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";

export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const RESET_PASSWORD_LOADING = "RESET_PASSWORD_LOADING";
export const RESET_PASSWORD_SUCESS = "RESET_PASSWORD_SUCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const COURSE_ADD_LOADING = "COURSE_ADD_LOADING";
export const COURSE_ADD_SUCESS = "COURSE_ADD_SUCESS";
export const COURSE_ADD_ERROR = "COURSE_ADD_ERROR";